#!/bin/bash
#
#  Copyright (c) 2019 Jeremy Cartwright
#  All rights reserved.
#  
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  
#  * Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#  
#  * Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#  
#  * Neither the name of Jeremy Cartwright nor the names of his
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#  
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
#  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
#  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#  Author: Jeremy Cartwright
# Contact: thebusker@hotmail.com 
# Created: Thu Dec 19 21:05:08 CST 2019
# cutty: a tool to slice mp3s with ffmpeg

input=$1
dir="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )/"

if [[ $1 ]]; then
	mkdir masters
	samdir="$(mkdir ~/sick\ beats/samples/no\ agenda/$input)"
	while read l; do
		src="$( echo $l | awk '{print $1 ".mp3"}')"
		dst="$( echo $l | awk '{print $2 ".mp3"}')"
		strt="$( echo $l | awk '{print $3}')"
		stp="$( echo $l | awk '{print $4}')"
		
		newcut="$(ffmpeg -i "$src" -ss "$strt" -to "$stp" -c copy "$dst" </dev/null)"
		mv $newcut $samdir
	done < "$dir$input"
	mv input masters
	mv *.mp3 masters
else
	echo
	echo "        cutty can't hang."
	echo "        Cutty is a tool to slice mp3s with ffmpeg."
	echo "        Cutty requires to be run in a directory with"
	echo "        Mp3s and a text file with timestamps and names,"
	echo "        and a single flag - the name of the txt file."
	echo
fi
