#!/bin/bash
#
# Author: Jeremy Cartwright
# Created: 28-Mar-2012
# Edited: 18-JAN-20
# header: prints a header for a new bash file,
#	  or a .py file if passed the -py flag.
#

app=$1
lang=$2
home="/home/$USER/"
py=".py"
nest="nest/"
scripts="scripts/"

edit() {
	cat $t
	echo -n "Would you like to edit $app? (Y/n): "
	read m

	if [[ $m == "Y" || "y" ]]; then
	   vim $t
	   exit 0
	else
	   echo "suits. Catch you on the flipside."
	   echo
	   exit 1
	fi
}

if [ $# -eq 1 ]; then
	t=$home$scripts$app
	touch $t
	echo "#!/bin/bash" > $t
	echo "#" >> $t
	echo "# Copyright: BSD 3 Clause License" >> $t
	echo "# https://github.com/cartwright/scripts/blob/master/LICENSE" >> $t
	echo "#" >> $t
	echo "#  Author: Jeremy Cartwright" >> $t
	echo "# Contact: thebusker@hotmail.com" >> $t
	echo "# Created:" `date` >> $t
	echo "# $app: " >> $t
	mkexe $t
	edit
elif [ "$lang" == "-py" ]; then
	t=$home$nest$app$py
	echo "#!/usr/bin/env python" > $t
	echo "#" >> $t
	echo "# Copyright: BSD 3 Clause License" >> $t
	echo "# https://github.com/cartwright/scripts/blob/master/LICENSE" >> $t
	echo "#" >> $t
	echo "#   Author: Jeremy Cartwright" >> $t
	echo "#  Contact: thebusker@hotmail.com" >> $t
	echo "#  Created: `date`" >> $t
	echo "#  $app: " >> $t
	echo 
	mkexe $t
	edit
else
	echo
	echo "header accepts 1 or 2 flags."
	echo
	echo "One flag will create a bash script named \$1 and launch vim."
	echo "Make a trailing -py flag to create a .py file named \$1.py and launch vim."
	echo
fi
