#!/bin/bash
#
#  Author: Jeremy Cartwright
# Contact: jeremy@tcjc8.com
# Created: Wed Jul 24 12:06:51 CDT 2013
# paclogChecker: 'e dodges bullets, Avi.

sed '1,/:: Starting/d' /var/log/paclog | wc -l
