#!/bin/bash
#
# Author: Jeremy Cartwright
# Contact: thebusker@hotmail.com
# Created:  Wed Apr 4 22:47:39 CDT 2012
# report: tow the line.

if [ $2 ]; then
	if [ $2 == '-c' ]; then
		a="/home/$USER/ubin/$1"
	fi
elif [ $1 ]; then
	a=~/scripts/$1
	if [ $a == "$USER" ]; then
		a="/home/$USER/scripts/$USER"
	fi
else a="/home/$USER/scripts/wrls"
fi

# header
echo "-------------------"
echo "______________________________________"
ls ~ --color=auto
echo "______________________________________"
echo "-------------------"
date
whoami
echo

# report
echo "************************************************************************" &&\
cat $a &&\
echo "************************************************************************" &&\
ls ~/scripts --color=auto &&\
echo "************************************************************************" &&\
#ls ~/ubin --color=auto

# footer
#echo
#echo
#echo
#echo "************************************************************************"
uname -a
echo "************************************************************************"

#
#
#
#
#
#########################################################################
