#!/usr/bin/perl -w
use strict;

$|=1;
print
        "Press <Enter> now, as this is a very stupid demo!\n",
        "Note that echo is not turned off, so you will see the answer here,\n",
        "even before perl has read it: ",
        "\x05"; # Ctrl-E -> tell Putty to identify itself
my $id=<STDIN>;
chomp $id;
print "OK, your terminal answered '$id' to Ctrl-E.\n"
