#!/bin/bash
#
#  Author: Jeremy Cartwright
# Contact: jeremy@tcjc8.com
# Created: Sun Nov 11 21:22:58 CST 2012
# testapp: a script to bring up and shut down the google app server testbed

app=$1
state=${2^^}

if [ $state = "UP" ]; then
	`python2.5 /usr/share/google_appengine/dev_appserver.py --use_sqlite -c --debug ~/go/$app/ &`
elif [ $state = "DOWN" ]; then
	py=`pgrep -f "python2.5 /usr/share/google_appengine/dev_appserver.py --use_sqlite -c --debug /home/jeremy/go/$app/"`
	if [ $py ]; then kill -9 $py; fi;
	sock=`pgrep -f ".*_jeremy_8080_go_app_work_dir/_go_app -addr_http tcp:127.0.0.1:.*"`
	if [ $sock ]; then kill -9 $sock; fi;
else
	echo "testapp accepts two parameters."
	echo "1) Name of App."
	echo "2) Up or Down."
fi
